In [1]:
# Loading libraries
import numpy as np

In [3]:
# Create an array
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# Manipulating array shapes
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# Flatten
print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
# Ravel
print(new_arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
# Transpose
print(new_arr.transpose())

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [13]:
# Stacking NumPy arrays
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
arr2 = 2*arr1
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [14]:
# Horizontal Stacking
arr3 = np.hstack((arr1,arr2))
print(arr3)
# Using Concatenate function
arr4 = np.concatenate((arr1,arr2), axis=1)
print(arr4)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [15]:
# Vertical stacking
arr5 = np.vstack((arr1,arr2))
print(arr5)
# Using Concatenate function
arr6 = np.concatenate((arr1,arr2), axis=0)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [16]:
# Depth stacking
arr7 = np.dstack((arr1,arr2))
print(arr7)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


In [18]:
# Partitioning NumPy arrays
# Horizontal splitting
arr_hor_split = np.hsplit(arr1, 3)
print(arr_hor_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [19]:
# Vertical splitting
arr_ver_split = np.vsplit(arr1, 3)
print(arr_ver_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [21]:
# Chaging data types of NumPy arrays
arr = arr.astype(float)
print(arr.dtype)

float64


In [22]:
# Convert to list
list1 = arr.tolist()
print(list1)

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]


In [23]:
# Creating copies
# Create no copy only assignment
arr_no_copy=arr
# Create Deep Copy
arr_copy=arr.copy()
# Create shallow copy using View
arr_view=arr.view()
print("Original Array: ",id(arr))
print("Assignment: ",id(arr_no_copy))
print("Deep Copy: ",id(arr_copy))
print("Shallow Copy(View): ",id(arr_view))

Original Array:  1528053924608
Assignment:  1528053924608
Deep Copy:  1528053669280
Shallow Copy(View):  1528053924928


In [26]:
# Creating a Dataframe
import pandas as pd
df = pd.read_csv('Datasets/WHO_first9cols.csv')
df.head()

Country  CountryID  Continent  Adolescent fertility rate (%)  \
0  Afghanistan          1          1                          151.0   
1      Albania          2          2                           27.0   
2      Algeria          3          3                            6.0   
3      Andorra          4          2                            NaN   
4       Angola          5          3                          146.0   

   Adult literacy rate (%)  \
0                     28.0   
1                     98.7   
2                     69.9   
3                      NaN   
4                     67.4   

   Gross national income per capita (PPP international $)  \
0                                                NaN        
1                                             6000.0        
2                                             5940.0        
3                                                NaN        
4                                             3890.0        

   Net primary school enrolment ratio female (%)  \
0                                            NaN   
1                                           93.0   
2                                           94.0   
3                                           83.0   
4                                           49.0   

   Net primary school enrolment ratio male (%)  \
0                                          NaN   
1                                         94.0   
2                                         96.0   
3                                         83.0   
4                                         51.0   

   Population (in thousands) total  
0                          26088.0  
1                           3172.0  
2                          33351.0  
3                             74.0  
4                          16557.0

In [27]:
# Describing Dataframes
# Describe the dataset
df.describe()

CountryID   Continent  Adolescent fertility rate (%)  \
count  202.000000  202.000000                     177.000000   
mean   101.500000    3.579208                      59.457627   
std     58.456537    1.808263                      49.105286   
min      1.000000    1.000000                       0.000000   
25%     51.250000    2.000000                      19.000000   
50%    101.500000    3.000000                      46.000000   
75%    151.750000    5.000000                      91.000000   
max    202.000000    7.000000                     199.000000   

       Adult literacy rate (%)  \
count               131.000000   
mean                 78.871756   
std                  20.415760   
min                  23.600000   
25%                  68.400000   
50%                  86.500000   
75%                  95.300000   
max                  99.800000   

       Gross national income per capita (PPP international $)  \
count                                         178.000000        
mean                                        11250.112360        
std                                         12586.753417        
min                                           260.000000        
25%                                          2112.500000        
50%                                          6175.000000        
75%                                         14502.500000        
max                                         60870.000000        

       Net primary school enrolment ratio female (%)  \
count                                     179.000000   
mean                                       84.033520   
std                                        17.788047   
min                                         6.000000   
25%                                        79.000000   
50%                                        90.000000   
75%                                        96.000000   
max                                       100.000000   

       Net primary school enrolment ratio male (%)  \
count                                   179.000000   
mean                                     85.698324   
std                                      15.451212   
min                                      11.000000   
25%                                      79.500000   
50%                                      90.000000   
75%                                      96.000000   
max                                     100.000000   

       Population (in thousands) total  
count                     1.890000e+02  
mean                      3.409964e+04  
std                       1.318377e+05  
min                       2.000000e+00  
25%                       1.328000e+03  
50%                       6.640000e+03  
75%                       2.097100e+04  
max                       1.328474e+06

In [28]:
# Count number of obs
df.count()

Country                                                   202
CountryID                                                 202
Continent                                                 202
Adolescent fertility rate (%)                             177
Adult literacy rate (%)                                   131
Gross national income per capita (PPP international $)    178
Net primary school enrolment ratio female (%)             179
Net primary school enrolment ratio male (%)               179
Population (in thousands) total                           189
dtype: int64

In [29]:
# Compute median
df.median()

CountryID                                                  101.5
Continent                                                    3.0
Adolescent fertility rate (%)                               46.0
Adult literacy rate (%)                                     86.5
Gross national income per capita (PPP international $)    6175.0
Net primary school enrolment ratio female (%)               90.0
Net primary school enrolment ratio male (%)                 90.0
Population (in thousands) total                           6640.0
dtype: float64

In [30]:
# Standard Deviation
df.std()

CountryID                                                     58.456537
Continent                                                      1.808263
Adolescent fertility rate (%)                                 49.105286
Adult literacy rate (%)                                       20.415760
Gross national income per capita (PPP international $)     12586.753417
Net primary school enrolment ratio female (%)                 17.788047
Net primary school enrolment ratio male (%)                   15.451212
Population (in thousands) total                           131837.708677
dtype: float64

In [ ]:
# Grouping and Joining Dataframes
